/**
 * Auth Action Constants
 * Used for AuthLog entries to ensure consistency
 */

const AUTH_ACTIONS = {
    // User Actions
    REGISTER: 'REGISTER',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGIN_BLOCKED: 'LOGIN_BLOCKED',
    LOGOUT: 'LOGOUT',
    REFRESH_TOKEN: 'REFRESH_TOKEN',
    EMAIL_VERIFIED: 'EMAIL_VERIFIED',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    PASSWORD_RESET: 'PASSWORD_RESET',
    OTP_RESENT: 'OTP_RESENT',

    // Admin Actions
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAILED: 'ADMIN_LOGIN_FAILED',
    ADMIN_LOGIN_BLOCKED: 'ADMIN_LOGIN_BLOCKED',
    ADMIN_LOGIN_DENIED: 'ADMIN_LOGIN_DENIED',
    ADMIN_PASSWORD_RESET: 'ADMIN_PASSWORD_RESET',
    USER_STATUS_UPDATED: 'USER_STATUS_UPDATED',
    USER_BLOCKED: 'USER_BLOCKED',
    USER_ACTIVATED: 'USER_ACTIVATED'
};

const OTP_TYPES = {
    EMAIL_VERIFY: 'email_verify',
    PASSWORD_RESET: 'password_reset',
    LOGIN: 'login'
};

module.exports = { AUTH_ACTIONS, OTP_TYPES };
